2022-10-19 10:46:56.290435: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-10-19 10:46:56.290522: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/home/mathis/envs/backward_ica/lib/python3.10/site-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/home/mathis/envs/backward_ica/lib/python3.10/site-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mathis/envs/backward_ica/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/home/mathis/envs/backward_ica/lib/python3.10/site-packages/tensorboard/main.py", line 39, in run_main
    main_lib.global_init()
  File "/home/mathis/envs/backward_ica/lib/python3.10/site-packages/tensorboard/main_lib.py", line 40, in global_init
    if getattr(tf, "__version__", "stub") == "stub":
  File "/home/mathis/envs/backward_ica/lib/python3.10/site-packages/tensorboard/lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
  File "/home/mathis/envs/backward_ica/lib/python3.10/site-packages/tensorboard/lazy.py", line 97, in wrapper
    cache[arg] = f(arg)
  File "/home/mathis/envs/backward_ica/lib/python3.10/site-packages/tensorboard/lazy.py", line 50, in load_once
    module = load_fn()
  File "/home/mathis/envs/backward_ica/lib/python3.10/site-packages/tensorboard/compat/__init__.py", line 45, in tf
    import tensorflow
  File "/home/mathis/envs/backward_ica/lib/python3.10/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/mathis/envs/backward_ica/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 45, in <module>
    from tensorflow.python.feature_column import feature_column_lib as feature_column
  File "/home/mathis/envs/backward_ica/lib/python3.10/site-packages/tensorflow/python/feature_column/feature_column_lib.py", line 18, in <module>
    from tensorflow.python.feature_column.feature_column import *
  File "/home/mathis/envs/backward_ica/lib/python3.10/site-packages/tensorflow/python/feature_column/feature_column.py", line 143, in <module>
    from tensorflow.python.layers import base
  File "/home/mathis/envs/backward_ica/lib/python3.10/site-packages/tensorflow/python/layers/base.py", line 16, in <module>
    from tensorflow.python.keras.legacy_tf_layers import base
  File "/home/mathis/envs/backward_ica/lib/python3.10/site-packages/tensorflow/python/keras/__init__.py", line 25, in <module>
    from tensorflow.python.keras import models
  File "/home/mathis/envs/backward_ica/lib/python3.10/site-packages/tensorflow/python/keras/models.py", line 20, in <module>
    from tensorflow.python.keras import metrics as metrics_module
  File "/home/mathis/envs/backward_ica/lib/python3.10/site-packages/tensorflow/python/keras/metrics.py", line 34, in <module>
    from tensorflow.python.keras import activations
  File "/home/mathis/envs/backward_ica/lib/python3.10/site-packages/tensorflow/python/keras/activations.py", line 18, in <module>
    from tensorflow.python.keras.layers import advanced_activations
  File "/home/mathis/envs/backward_ica/lib/python3.10/site-packages/tensorflow/python/keras/layers/__init__.py", line 22, in <module>
    from tensorflow.python.keras.engine.input_layer import Input
  File "/home/mathis/envs/backward_ica/lib/python3.10/site-packages/tensorflow/python/keras/engine/input_layer.py", line 24, in <module>
    from tensorflow.python.keras.engine import base_layer
  File "/home/mathis/envs/backward_ica/lib/python3.10/site-packages/tensorflow/python/keras/engine/base_layer.py", line 45, in <module>
    from tensorflow.python.keras import constraints
  File "/home/mathis/envs/backward_ica/lib/python3.10/site-packages/tensorflow/python/keras/constraints.py", line 336, in <module>
    @keras_export('keras.constraints.get')
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/mathis/repos/backward_ica/train_multiple_models.py", line 61, in <module>
    tensorboard_process.wait()
  File "/usr/lib/python3.10/subprocess.py", line 1207, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1941, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.10/subprocess.py", line 1899, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
